name: "modelo_con_sin_mascarilla"
platform: "onnxruntime_onnx"
default_model_filename: "modelo_con_sin_mascarilla.onnx"
max_batch_size: 32
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

dynamic_batching {
  preferred_batch_size: [ 1, 2, 4, 8, 16, 32 ]
  max_queue_delay_microseconds: 100
}
